DevCube.Website/ViewModels/CreateProgrammerViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using DevCube.Website.Validators;

namespace DevCube.Website.ViewModels
{
    public class CreateProgrammerViewModel
    {
        public int ProgrammerID { get; set; }

        [Required(ErrorMessage = "First name is required")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "First Name should be between 3 and 50 characters")]
        [DuplicateNameValidator(ErrorMessage = "this guy already exists")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Last name is required")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Last Name should be between 3 and 50 characters")]
        public string LastName { get; set; }

        public bool IsChecked { get; set; }

        public List<CreateSkillViewModel> Skills { get; set; }
    }
}

DevCube.Website/ViewModels/ProgrammerViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using DevCube.Website.Validators;

namespace DevCube.Website.ViewModels
{
    public class ProgrammerViewModel
    {
        public int ProgrammerID { get; set; }

        [Required(ErrorMessage = "First name is required")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "First Name should be between 3 and 50 characters")]
        [DuplicateNameValidator(ErrorMessage = "this guy already exists")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Last name is required")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Last Name should be between 3 and 50 characters")]
        public string LastName { get; set; }

        public bool IsChecked { get; set; }

        public List<SkillViewModel> Skills { get; set; }
    }
}

DevCube.Website/ViewModels/UpdateProgrammerViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace DevCube.Website.ViewModels
{
    public class UpdateProgrammerViewModel
    {
        public int ProgrammerID { get; set; }

        [Required(ErrorMessage = "First name is required")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "First Name should be between 3 and 50 characters")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Last name is required")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Last Name should be between 3 and 50 characters")]
        public string LastName { get; set; }

        public bool IsChecked { get; set; }

        public List<CreateSkillViewModel> Skills { get; set; }
    }
}

DevCube.Website/Controllers/ProgrammerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Diagnostics;
using X.PagedList;
using X.PagedList.Mvc;
using DevCube.Data;
using DevCube.Models;
using DevCube.Website.ViewModels;


namespace DevCube.Controllers
{
    public class ProgrammerController : Controller
    {
        //INDEX
        [HttpGet]
        public ActionResult IndexProgrammer(int? page)
        {
            var programmers = ProgrammerData.SelectAllProgrammers()
                .OrderBy(x => x.FirstName);

            var programmerViewModelInstance = (from p in programmers
                                               select new ProgrammerModel()
                                               {
                                                   ProgrammerID = p.ProgrammerID,
                                                   FirstName = p.FirstName,
                                                   LastName = p.LastName,

                                                   Skills = (from s in p.Skills
                                                             select new SkillModel()
                                                             {
                                                                 SkillID = s.SkillID,
                                                                 Name = s.Name
                                                             }).ToList()
                                               }).ToPagedList(page ?? 1, 10);

            return View(programmerViewModelInstance);
        }

        [HttpPost]
        public ActionResult IndexProgrammer(string name, string skillName)
        {
            var programmers = ProgrammerData.SelectAllProgrammers(name, skillName)
                   .OrderBy(x => x.FirstName);

            var programmerViewModelInstance = (from p in programmers
                                               select new ProgrammerModel()
                                               {
                                                   ProgrammerID = p.ProgrammerID,
                                                   FirstName = p.FirstName,
                                                   LastName = p.LastName,

                                                   Skills = (from s in p.Skills
                                                             select new SkillModel()
                                                             {
                                                                 SkillID = s.SkillID,
                                                                 Name = s.Name
                                                             }).ToList()
                                               }).ToPagedList(1, 10);

            ViewData["programmerNameSearchField"] = name;

            ViewData["skillNameSearchField"] = skillName;

            return View(programmerViewModelInstance);
        }

        //CREATE
        [HttpGet]
        public ActionResult CreateProgrammer()
        {
            var programmerModelInstance = (new CreateProgrammerViewModel()
            {
                Skills = (from s in SkillData.SelectAllSkills()
                          select new CreateSkillViewModel()
                          {
                              SkillID = s.SkillID,
                              Name = s.Name,
                          }).ToList()
            });

            return View(programmerModelInstance);
        }

        [HttpPost]
        public ActionResult CreateProgrammer(CreateProgrammerViewModel programmer, List<int> skillIDs)
        {
            if (ModelState.IsValid)
            {

                ProgrammerData.CreateProgrammer(programmer.FirstName, programmer.LastName, skillIDs);

                return RedirectToAction("IndexProgrammer");
            }
            else
            {
                var programmerModelInstance = (new CreateProgrammerViewModel()
                {
                    Skills = (from s in SkillData.SelectAllSkills()
                              select new CreateSkillViewModel()
                              {
                                  SkillID = s.SkillID,
                                  Name = s.Name,
                              }).ToList()
                });

                return View(programmerModelInstance);
            }
        }

        //UPDATE   
        [HttpGet]
        [HandleError]
        public ActionResult UpdateProgrammer(int? id)
        {
            var programmerData = ProgrammerData.SelectProgrammerByID(id);

            var programmerSkills = programmerData.Skills.Select(s => s.SkillID).ToList();

            var skills = (from s in SkillData.SelectAllSkills()
                          select new CreateSkillViewModel()
                          {
                              SkillID = s.SkillID,
                              Name = s.Name,
                              IsChecked = false
                          }).ToList();

            var programmer = new UpdateProgrammerViewModel()
            {
                ProgrammerID = programmerData.ProgrammerID,
                FirstName = programmerData.FirstName,
                LastName = programmerData.LastName,
            };

            //Sets known Skills to be checked and the unknown Skill uncheked
            foreach (var s in skills)
            {
                if (programmerSkills.Contains(s.SkillID))
                {
                    s.IsChecked = true;
                }
            }

            programmer.Skills = skills;

            return View(programmer);
        }

        [HttpPost]
        public ActionResult UpdateProgrammer(UpdateProgrammerViewModel programmerViewModel, List<int> skillIDs)
        {
            if (ModelState.IsValid)
            {
                var programmerModel = new ProgrammerModel()
                {
                    ProgrammerID = programmerViewModel.ProgrammerID,
                    FirstName = programmerViewModel.FirstName,
                    LastName = programmerViewModel.LastName
                };

                ProgrammerData.UpdateProgrammer(programmerModel, skillIDs);

                return RedirectToAction("IndexProgrammer");
            }
            else
            {
                var programmerData = ProgrammerData.SelectProgrammerByID(programmerViewModel.ProgrammerID);

                var programmerSkills = programmerData.Skills.Select(s => s.SkillID).ToList();

                var programmer = new UpdateProgrammerViewModel()
                {
                    ProgrammerID = programmerData.ProgrammerID,
                    FirstName = programmerData.FirstName,
                    LastName = programmerData.LastName
                };

                var allSkills = (from s in SkillData.SelectAllSkills()
                                 select new CreateSkillViewModel()
                                 {
                                     SkillID = s.SkillID,
                                     Name = s.Name,
                                     IsChecked = false
                                 }).ToList();

                //Sets known Skills to be checked and the unknown Skill uncheked
                foreach (var s in allSkills)
                {
                    if (programmerSkills.Contains(s.SkillID))
                    {
                        s.IsChecked = true;
                    }
                }

                programmer.Skills = allSkills;

                return View(programmer);
            }
        }

        //DELETE
        [HttpPost]
        public ActionResult DeleteProgrammer(int id)
        {
            ProgrammerData.DeleteProgrammer(id);

            return Json("");
        }
    }
}

DevCube.Website/Controllers/SkillController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Diagnostics;
using DevCube.Data;
using DevCube.Models;
using DevCube.Website.ViewModels;


namespace DevCube.Controllers
{
    public class SkillController : Controller
    {
        //INDEX
        [HttpGet]
        public ActionResult IndexSkill()
        {
            var skills = SkillData.SelectAllSkills()
                .OrderBy(x => x.Name).ToList();

            return View(skills);
        }

        [HttpPost]
        public ActionResult IndexSkill(string name, string programmerName)
        {
            var filteredSkillsByName = SkillData.SelectAllSkills(name, programmerName)
                .OrderBy(x => x.Name).ToList();

            return View(filteredSkillsByName);
        }

        //CREATE
        [HttpGet]
        public ActionResult CreateSkill()
        {
            var skillModelInstance = (new CreateSkillViewModel()
            {
                Programmers = (from p in ProgrammerData.SelectAllProgrammers()
                               select new CreateProgrammerViewModel()
                               {
                                   ProgrammerID = p.ProgrammerID,
                                   FirstName = p.FirstName,
                                   LastName = p.LastName,
                               }).ToList()
            });

            return View(skillModelInstance);
        }

        [HttpPost]
        public ActionResult CreateSkill(CreateSkillViewModel skill, List<int> programmerIDs)
        {
            if (ModelState.IsValid)
            {
                SkillData.CreateSkill(skill.Name, programmerIDs);

                return RedirectToAction("IndexSkill");
            }
            else
            {
                var skillModelInstance = (new CreateSkillViewModel()
                {
                    Programmers = (from p in ProgrammerData.SelectAllProgrammers()
                                   select new CreateProgrammerViewModel()
                                   {
                                       ProgrammerID = p.ProgrammerID,
                                       FirstName = p.FirstName,
                                       LastName = p.LastName,
                                   }).ToList()
                });

                return View(skillModelInstance);
            }
        }

        //UPDATE
        [HttpGet]
        [HandleError]
        public ActionResult UpdateSkill(int? id)
        {
            var skillData = SkillData.SelectSkillByID(id);

            var programmerSkills = skillData.Programmers.Select(p => p.ProgrammerID).ToList();

            var programmers = (from p in ProgrammerData.SelectAllProgrammers()
                               select new CreateProgrammerViewModel()
                               {
                                   ProgrammerID = p.ProgrammerID,
                                   FirstName = p.FirstName,
                                   LastName = p.LastName,
                                   IsChecked = false
                               }).ToList();

            var skill = new UpdateSkillViewModel()
            {
                SkillID = skillData.SkillID,
                Name = skillData.Name

            };

            //Sets Programmers thet know the Skill to be checked and the those who doesnt unchekeds
            foreach (var p in programmers)
            {
                if (programmerSkills.Contains(p.ProgrammerID))
                {
                    p.IsChecked = true;
                }
            }

            skill.Programmers = programmers;

            return View(skill);
        }

        [HttpPost]
        public ActionResult UpdateSkill(UpdateSkillViewModel skillViewModel, List<int> programmerIDs)
        {
            if (ModelState.IsValid)
            {
                var skillModel = new SkillModel()
                {
                    SkillID = skillViewModel.SkillID,
                    Name = skillViewModel.Name
                };

                SkillData.UpdateSkill(skillModel, programmerIDs);

                return RedirectToAction("IndexSkill");
            }
            else
            {
                var skillData = SkillData.SelectSkillByID(skillViewModel.SkillID);

                var programmerSkills = skillData.Programmers.Select(p => p.ProgrammerID).ToList();

                var programmers = (from p in ProgrammerData.SelectAllProgrammers()
                                   select new CreateProgrammerViewModel()
                                   {
                                       ProgrammerID = p.ProgrammerID,
                                       FirstName = p.FirstName,
                                       LastName = p.LastName,
                                       IsChecked = false
                                   }).ToList();

                var skill = new UpdateSkillViewModel()
                {
                    SkillID = skillData.SkillID,
                    Name = skillData.Name

                };

                //Sets Programmers thet know the Skill to be checked and the those who doesnt unchekeds
                foreach (var p in programmers)
                {
                    if (programmerSkills.Contains(p.ProgrammerID))
                    {
                        p.IsChecked = true;
                    }
                }

                skill.Programmers = programmers;

                return View(skill);
            }
        }
        //DELETE
        [HttpPost]
        public ActionResult DeleteSkill(int id)
        {
            SkillData.DeleteSkill(id);

            return Json("");
        }
    }
}

DevCube.Website/Views/Programmer/CreateProgrammer.cshtml
@model ProgrammerViewModel

@{
    ViewBag.Title = "Create";
}

<!--Title-->
<h2>Add Programmer</h2>

<!--Forms-->
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />

    <!--Programmer Forms-->
    <div class="form-group">
        <p>First Name</p>
        @Html.EditorFor(modelItem => modelItem.FirstName, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(modelItem => modelItem.FirstName, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        <p>Last Name</p>
        @Html.EditorFor(modelItem => modelItem.LastName, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(modelItem => modelItem.LastName, "", new { @class = "text-danger" })
    </div>

    <h4>Select Skills</h4>

    <!--Note-->
    <div class="alert alert-info"><strong>Note:</strong> You can leave the programmer without knowing any skill</div>
    <hr />

    <!--Skill Forms-->
    <div class="form-group">
        @foreach (var skills in Model.Skills)
        {
            <label>@skills.Name</label>
            <input type="checkbox" name="SkillIDs" value="@skills.SkillID" checked="@skills.IsChecked" />
            <br />
        }
    </div>

    <!--Submit-->
    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-default" />
    </div>
</div>
}
<div>
    @Html.ActionLink("Back to List", "IndexProgrammer")
</div>

DevCube.Website/Views/Programmer/IndexProgrammer.cshtml
@model IPagedList<ProgrammerModel>

@{
    ViewBag.Title = "Programmers";
}

<!--Jumbotron-->
<div class="jumbotron">
    <h1>Dev-Cube<img src="~/Content/images/logo.png"></h1>
    <p class="lead">Dev-Cube is an application for simplifying employee managment by providing listing with all the avaible employees and their skills.</p>
    @Html.ActionLink("Skills", "IndexSkill", "Skill", null, new { @id = "button", @class = "btn btn-lg" })
    @Html.ActionLink("Get back", "IndexProgrammer", "Programmer", null, new { @id = "button", @class = "btn btn-lg" })
</div>

<!--Search Fields-->
@using (Html.BeginForm())
{
    <div id="search-form">
        <div class="form-group">
            <div class="container">
                <div class="row">
                    <div class="col-5">
                        <label for="search-form_input_name"><strong>Search by Name</strong></label>
                    </div>
                    <div class="col-7">
                        <input id="search-form_input_name" class="form-control" type="text" name="name" value="@ViewData["programmerNameSearchField"]" placeholder="Search..." />
                    </div>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="container">
                <div class="row">
                    <div class="col-5">
                        <label for="search-form_input"><strong>Search by Skill</strong></label>
                    </div>
                    <div class="col-7">
                        <input id="search-form_input_ame" class="form-control" type="text" name="skillName" value="@ViewData["skillNameSearchField"]" placeholder="Search..." />
                    </div>
                </div>
            </div>
        </div>
        <input id="search-form_submitButton" class="btn btn-md" type="submit" />
    </div>
}

<!--Title-->
<h2>Programmers</h2>

<!--Create Link-->
<p>From here you can manage your programmers and their known skills</p>
@Html.ActionLink("Add New Programmer", "CreateProgrammer", null, new { @id = "button", @class = "btn btn-sm" })

<!--Table-->
<div class="table-responsive">
    <table class="table table-dark  table-hover">
        <thead class="thead-dark">
            @if (Model.Count() != 0)
            {
                <tr>
                    <th>
                        First Name
                    </th>

                    <th>
                        Last Name
                    </th>

                    <th>
                        Skills
                    </th>

                    <th>
                        Manage
                    </th>

                </tr>
            }
            else
            {
                <div id="alert-container">
                    <div class="alert alert-danger"><strong>Hmmmm, seems we cant find what you are looking for, try typing something else in the search box</strong></div>
                </div>
            }
        </thead>

        @foreach (var item in Model)
        {
            int i = 0;
            <tr>

                <td>
                    @item.FirstName
                </td>

                <td>
                    @item.LastName
                </td>

                <td>
                    @if (item.Skills.Count == 0)
                    {
                        <span><strong>This "programmer" doesnt know any skill</strong></span>
                    }

                    @foreach (var skill in item.Skills)
                    {
                        i++;

                        string skillName = String.Concat(skill.Name, ", ");

                        if (i == item.Skills.Count())
                        {
                            skillName = skill.Name;
                        }

                        @skillName

                    }

                </td>

                <td>
                    @Html.ActionLink("Update", "UpdateProgrammer", new { id = item.ProgrammerID, pageNumber = Model.PageNumber}) |
                    <a data-id="@item.ProgrammerID" class="delete-link" href="#" data-toggle="modal" data-target="#Modal">Delete</a>
                </td>

            </tr>
        }
    </table>
</div>

<!--Pagination-->
@Html.PagedListPager(Model, page => Url.Action("IndexProgrammer", new { page }), Bootstrap4PagedListRenderOptions.ClassicPlusFirstAndLast)

<!--Modal-->
<div class="modal fade" id="Modal" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Woah There!</h5>
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Are you sure you want to delete this programmer!
                @Html.Hidden("id", "", new { @class = "hidden-field" })
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
                <button id="delete-button" class="btn btn-default">Yes</button>
            </div>
        </div>
    </div>
</div>

<!--Scripts-->
<script type="text/javascript">
    let Url = '@Url.Action("DeleteProgrammer", "Programmer")';
</script>

@Scripts.Render("~/Content/js/delete.js")

DevCube.Website/Views/Programmer/UpdateProgrammer.cshtml
@model UpdateProgrammerViewModel

@{
    ViewBag.Title = "Update";
}

<!--Title-->
<h2>Update</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <!--Forms-->
    <div class="form-horizontal">
        <h4>Programmer's known skills</h4>
        <hr />

        <div class="form-group">
            @Html.HiddenFor(modelItem => modelItem.ProgrammerID)

            <label><strong>First Name:</strong></label>
            @Html.EditorFor(modelItem => modelItem.FirstName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(modelItem => modelItem.FirstName, "", new { @class = "text-danger" })
            <br />
            
            <label><strong>Last Name:</strong></label>
            @Html.EditorFor(modelItem => modelItem.LastName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(modelItem => modelItem.LastName, "", new { @class = "text-danger" })
            <br />


            @foreach (var skills in Model.Skills)
            {
                @skills.Name
                <input type="checkbox" name="SkillIDs" value="@skills.SkillID" checked="@skills.IsChecked" />
                <br />
            }
        </div>

        <!--Submit-->
        <div class="form-group">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "IndexProgrammer", null, new { @id = "button", @class = "btn btn-sm" })
</div>